services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=30d'
    depends_on:
      - ping-exporter
    network_mode: host

  # Ping Exporter (czerwonk) с поддержкой ICMP
  
  ping-exporter:
    image: czerwonk/ping_exporter
    container_name: ping-exporter
    ports:
      - "9427:9427"
    volumes:
      - ./ping-targets.yml:/config/config.yml  # Конфиг целей для пинга
    cap_add:  # Требуются права для RAW-сокетов
      - NET_RAW
    security_opt:
      - apparmor:unconfined
    mem_limit: 128M
    restart: unless-stopped
    network_mode: host
    

  # Grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./camera-mapping.csv:/usr/share/grafana/public/camera-mapping.csv
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    network_mode: host

  # Alertmanager
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    network_mode: host

volumes:
  grafana-storage:
  prometheus-data:
