global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'ping-exporter'
    static_configs:
      - targets: ['localhost:9427']
    metrics_path: /metrics
    scrape_interval: 30s

rule_files:
  - /etc/prometheus/alert.rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']